/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

/**
 *
 * @author DANIELAROSERO
 */
public class VPrincipal extends javax.swing.JFrame{

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
    initComponents();
    JPanel objPanel = new ClaseAdaptada1();
    objPanel.setSize(pnlContainer.getWidth(), pnlContainer.getHeight());
    pnlContainer.add(objPanel);
    pnlContainer.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        pnlContainer = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opusuarios = new javax.swing.JMenu();
        agregarUsuario = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Opconcesionaria = new javax.swing.JMenu();
        Opmotos = new javax.swing.JMenu();
        Opproforma = new javax.swing.JMenu();
        Oppedidos = new javax.swing.JMenu();
        Opventas = new javax.swing.JMenu();
        Opreportes = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        pnlContainer.setMaximumSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );

        Opusuarios.setText("Usuarios");

        agregarUsuario.setText("Nuevo");
        Opusuarios.add(agregarUsuario);

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Opusuarios.add(jMenuItem2);

        jMenuItem3.setText("Buscar");
        Opusuarios.add(jMenuItem3);

        jMenuItem1.setText("Dar de Baja");
        Opusuarios.add(jMenuItem1);

        jMenuBar1.add(Opusuarios);

        Opconcesionaria.setText("Concesionarias");
        jMenuBar1.add(Opconcesionaria);

        Opmotos.setText("Motos");
        jMenuBar1.add(Opmotos);

        Opproforma.setText("Proformas");
        jMenuBar1.add(Opproforma);

        Oppedidos.setText("Pedidos");
        jMenuBar1.add(Oppedidos);

        Opventas.setText("Ventas");
        jMenuBar1.add(Opventas);

        Opreportes.setText("Reportes");
        jMenuBar1.add(Opreportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new VPrincipal().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Opconcesionaria;
    private javax.swing.JMenu Opmotos;
    private javax.swing.JMenu Oppedidos;
    private javax.swing.JMenu Opproforma;
    private javax.swing.JMenu Opreportes;
    private javax.swing.JMenu Opusuarios;
    private javax.swing.JMenu Opventas;
    private javax.swing.JMenuItem agregarUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel pnlContainer;
    // End of variables declaration//GEN-END:variables
}
